# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 649)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Boton_Aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_Aceptar.setGeometry(QtCore.QRect(420, 560, 91, 31))
        self.Boton_Aceptar.setObjectName("Boton_Aceptar")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(70, 300, 791, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_brp = QtWidgets.QWidget()
        self.tab_brp.setObjectName("tab_brp")
        self.label_3 = QtWidgets.QLabel(self.tab_brp)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 81, 71))
        self.label_3.setStyleSheet("border-image: url(:/brp/BRP_inc_logo.svg.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.ruta_fichero_1_brp = QtWidgets.QLineEdit(self.tab_brp)
        self.ruta_fichero_1_brp.setEnabled(False)
        self.ruta_fichero_1_brp.setGeometry(QtCore.QRect(190, 110, 431, 25))
        self.ruta_fichero_1_brp.setObjectName("ruta_fichero_1_brp")
        self.busca_fichero_1_brp = QtWidgets.QPushButton(self.tab_brp)
        self.busca_fichero_1_brp.setEnabled(False)
        self.busca_fichero_1_brp.setGeometry(QtCore.QRect(660, 110, 89, 25))
        self.busca_fichero_1_brp.setObjectName("busca_fichero_1_brp")
        self.ruta_fichero_2_brp = QtWidgets.QLineEdit(self.tab_brp)
        self.ruta_fichero_2_brp.setEnabled(False)
        self.ruta_fichero_2_brp.setGeometry(QtCore.QRect(190, 150, 431, 25))
        self.ruta_fichero_2_brp.setObjectName("ruta_fichero_2_brp")
        self.busca_fichero_2_brp = QtWidgets.QPushButton(self.tab_brp)
        self.busca_fichero_2_brp.setEnabled(False)
        self.busca_fichero_2_brp.setGeometry(QtCore.QRect(660, 150, 89, 25))
        self.busca_fichero_2_brp.setObjectName("busca_fichero_2_brp")
        self.label_12 = QtWidgets.QLabel(self.tab_brp)
        self.label_12.setGeometry(QtCore.QRect(180, 30, 491, 31))
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.tab_brp)
        self.label_15.setGeometry(QtCore.QRect(30, 100, 161, 41))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_brp)
        self.label_16.setGeometry(QtCore.QRect(30, 140, 161, 41))
        self.label_16.setObjectName("label_16")
        self.Activa_brp = QtWidgets.QRadioButton(self.tab_brp)
        self.Activa_brp.setGeometry(QtCore.QRect(110, 70, 112, 23))
        self.Activa_brp.setObjectName("Activa_brp")
        self.tabWidget.addTab(self.tab_brp, "")
        self.tab_beta = QtWidgets.QWidget()
        self.tab_beta.setObjectName("tab_beta")
        self.ruta_fichero_beta = QtWidgets.QLineEdit(self.tab_beta)
        self.ruta_fichero_beta.setEnabled(False)
        self.ruta_fichero_beta.setGeometry(QtCore.QRect(200, 140, 431, 25))
        self.ruta_fichero_beta.setObjectName("ruta_fichero_beta")
        self.busca_fichero_beta = QtWidgets.QPushButton(self.tab_beta)
        self.busca_fichero_beta.setEnabled(False)
        self.busca_fichero_beta.setGeometry(QtCore.QRect(670, 140, 89, 25))
        self.busca_fichero_beta.setObjectName("busca_fichero_beta")
        self.label_9 = QtWidgets.QLabel(self.tab_beta)
        self.label_9.setGeometry(QtCore.QRect(20, 20, 141, 91))
        self.label_9.setStyleSheet("border-image: url(:/beta_1/Beta-Logo.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.tab_beta)
        self.label_13.setGeometry(QtCore.QRect(180, 40, 491, 31))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_beta)
        self.label_14.setGeometry(QtCore.QRect(40, 130, 161, 41))
        self.label_14.setObjectName("label_14")
        self.Activa_beta = QtWidgets.QRadioButton(self.tab_beta)
        self.Activa_beta.setGeometry(QtCore.QRect(170, 90, 112, 23))
        self.Activa_beta.setObjectName("Activa_beta")
        self.tabWidget.addTab(self.tab_beta, "")
        self.tab_sp_brp = QtWidgets.QWidget()
        self.tab_sp_brp.setObjectName("tab_sp_brp")
        self.logo = QtWidgets.QLabel(self.tab_sp_brp)
        self.logo.setGeometry(QtCore.QRect(40, 30, 81, 61))
        self.logo.setStyleSheet("border-image: url(:/brp/BRP_inc_logo.svg.png);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.Tipo_brp = QtWidgets.QLineEdit(self.tab_sp_brp)
        self.Tipo_brp.setEnabled(False)
        self.Tipo_brp.setGeometry(QtCore.QRect(290, 80, 401, 25))
        self.Tipo_brp.setObjectName("Tipo_brp")
        self.Anyo_brp = QtWidgets.QLineEdit(self.tab_sp_brp)
        self.Anyo_brp.setEnabled(False)
        self.Anyo_brp.setGeometry(QtCore.QRect(530, 20, 111, 25))
        self.Anyo_brp.setObjectName("Anyo_brp")
        self.Modelo_brp = QtWidgets.QLineEdit(self.tab_sp_brp)
        self.Modelo_brp.setEnabled(False)
        self.Modelo_brp.setGeometry(QtCore.QRect(290, 140, 401, 25))
        self.Modelo_brp.setObjectName("Modelo_brp")
        self.label_5 = QtWidgets.QLabel(self.tab_sp_brp)
        self.label_5.setGeometry(QtCore.QRect(190, 70, 101, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_sp_brp)
        self.label_6.setGeometry(QtCore.QRect(465, 10, 51, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_sp_brp)
        self.label_7.setGeometry(QtCore.QRect(190, 130, 81, 41))
        self.label_7.setObjectName("label_7")
        self.Activa_spider_brp = QtWidgets.QRadioButton(self.tab_sp_brp)
        self.Activa_spider_brp.setGeometry(QtCore.QRect(30, 120, 112, 23))
        self.Activa_spider_brp.setObjectName("Activa_spider_brp")
        self.label_11 = QtWidgets.QLabel(self.tab_sp_brp)
        self.label_11.setGeometry(QtCore.QRect(190, 10, 101, 41))
        self.label_11.setObjectName("label_11")
        self.product = QtWidgets.QComboBox(self.tab_sp_brp)
        self.product.setGeometry(QtCore.QRect(290, 20, 141, 25))
        self.product.setObjectName("product")
        self.tabWidget.addTab(self.tab_sp_brp, "")
        self.tab_sp_beta = QtWidgets.QWidget()
        self.tab_sp_beta.setObjectName("tab_sp_beta")
        self.label_8 = QtWidgets.QLabel(self.tab_sp_beta)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 141, 91))
        self.label_8.setStyleSheet("border-image: url(:/beta_1/Beta-Logo.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.Beta_motos = QtWidgets.QPlainTextEdit(self.tab_sp_beta)
        self.Beta_motos.setEnabled(False)
        self.Beta_motos.setGeometry(QtCore.QRect(170, 70, 401, 81))
        self.Beta_motos.setObjectName("Beta_motos")
        self.Activa_spider_beta = QtWidgets.QRadioButton(self.tab_sp_beta)
        self.Activa_spider_beta.setGeometry(QtCore.QRect(590, 90, 112, 23))
        self.Activa_spider_beta.setObjectName("Activa_spider_beta")
        self.label_10 = QtWidgets.QLabel(self.tab_sp_beta)
        self.label_10.setGeometry(QtCore.QRect(150, 10, 591, 41))
        self.label_10.setObjectName("label_10")
        self.Activa_spider_beta_2 = QtWidgets.QRadioButton(self.tab_sp_beta)
        self.Activa_spider_beta_2.setGeometry(QtCore.QRect(590, 120, 121, 23))
        self.Activa_spider_beta_2.setObjectName("Activa_spider_beta_2")
        self.ruta_fichero_beta_2 = QtWidgets.QLineEdit(self.tab_sp_beta)
        self.ruta_fichero_beta_2.setEnabled(False)
        self.ruta_fichero_beta_2.setGeometry(QtCore.QRect(170, 170, 431, 25))
        self.ruta_fichero_beta_2.setObjectName("ruta_fichero_beta_2")
        self.label_17 = QtWidgets.QLabel(self.tab_sp_beta)
        self.label_17.setGeometry(QtCore.QRect(10, 160, 161, 41))
        self.label_17.setObjectName("label_17")
        self.busca_fichero_beta_2 = QtWidgets.QPushButton(self.tab_sp_beta)
        self.busca_fichero_beta_2.setEnabled(False)
        self.busca_fichero_beta_2.setGeometry(QtCore.QRect(640, 170, 89, 25))
        self.busca_fichero_beta_2.setObjectName("busca_fichero_beta_2")
        self.tabWidget.addTab(self.tab_sp_beta, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 20, 261, 121))
        self.label.setStyleSheet("border-image: url(:/enduro/endurorecambios.png);")
        self.label.setObjectName("label")
        self.Display = QtWidgets.QTextBrowser(self.centralwidget)
        self.Display.setGeometry(QtCore.QRect(10, 10, 491, 261))
        self.Display.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Display.setObjectName("Display")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(530, 160, 181, 41))
        self.label_18.setObjectName("label_18")
        self.busca_inventario = QtWidgets.QPushButton(self.centralwidget)
        self.busca_inventario.setEnabled(True)
        self.busca_inventario.setGeometry(QtCore.QRect(750, 170, 89, 25))
        self.busca_inventario.setObjectName("busca_inventario")
        self.ruta_inventario = QtWidgets.QLineEdit(self.centralwidget)
        self.ruta_inventario.setEnabled(True)
        self.ruta_inventario.setGeometry(QtCore.QRect(520, 220, 411, 25))
        self.ruta_inventario.setObjectName("ruta_inventario")
        self.tabWidget.raise_()
        self.Boton_Aceptar.raise_()
        self.label.raise_()
        self.Display.raise_()
        self.label_18.raise_()
        self.busca_inventario.raise_()
        self.ruta_inventario.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 954, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Minemas"))
        self.Boton_Aceptar.setText(_translate("MainWindow", "Aceptar"))
        self.busca_fichero_1_brp.setText(_translate("MainWindow", "..."))
        self.busca_fichero_2_brp.setText(_translate("MainWindow", "..."))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; text-decoration: underline;\">Actualización de tarifas y Creación Artículos.</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Fichero Tarifa</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Fichero Tarifa</span></p></body></html>"))
        self.Activa_brp.setText(_translate("MainWindow", "Activar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_brp), _translate("MainWindow", "Tarifa BRP"))
        self.busca_fichero_beta.setText(_translate("MainWindow", "..."))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; text-decoration: underline;\">Actualización de tarifas y Creación Artículos.</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Fichero Tarifa</span></p></body></html>"))
        self.Activa_beta.setText(_translate("MainWindow", "Activar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_beta), _translate("MainWindow", "Tarifa Beta"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Categoria:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Año:</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Modelo:</span></p></body></html>"))
        self.Activa_spider_brp.setText(_translate("MainWindow", "Activar"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Producto:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sp_brp), _translate("MainWindow", "Despiece BRP"))
        self.Activa_spider_beta.setText(_translate("MainWindow", "Activar"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ef2929;\">Un modelo de moto en cada línea.</span></p></body></html>"))
        self.Activa_spider_beta_2.setText(_translate("MainWindow", "Subir a la web"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Fichero Tarifa</span></p></body></html>"))
        self.busca_fichero_beta_2.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sp_beta), _translate("MainWindow", "Despiece BETA"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Display.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#c4a000;\">Bienvenido a Minemas Enduro!!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">    </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#4e9a06;\">    Rellena las pestañas con las acciones a realizar.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#4e9a06;\">    Tarifa BRP =&gt; Actualiza las tarifas de PRB.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#4e9a06;\">    Tarifa Beta =&gt; Actualiza las tarifas de Beta.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#4e9a06;\">    Despiece BRP =&gt; Descarga despieces de BRP.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#4e9a06;\">    Despiece Beta =&gt; Descarga despieces de Beta.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Fichero Inventario</span></p></body></html>"))
        self.busca_inventario.setText(_translate("MainWindow", "..."))
import enduro_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
